name: grover_analytics

version: 1.0.0

profile: my-snowflake-db

model-paths: ["analytics/models"]

models:
  grover_analytics:
    bronze:
      +schema: ods_production
      +materialized: table
    gold:
      +schema: master
      +materialized: view